# Generated by Django 3.2.9 on 2021-12-01 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('kitchen_type', models.CharField(max_length=120)),
                ('img_path', models.CharField(max_length=255)),
                ('street', models.CharField(max_length=120)),
                ('local_number', models.CharField(max_length=120)),
                ('city', models.CharField(max_length=120)),
                ('pass_code', models.IntegerField(max_length=5)),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owns', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
