# Generated by Django 3.2.9 on 2021-12-01 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='owner_id',
            new_name='owner',
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='pass_code',
            field=models.IntegerField(),
        ),
    ]
