# Generated by Django 3.2.9 on 2021-12-03 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_auto_20211201_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='img_path',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
