# Generated by Django 3.2.9 on 2021-12-12 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zamowienia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zamowienia',
            name='cena',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='zamowienia',
            name='email',
            field=models.EmailField(default='email', max_length=254),
        ),
        migrations.AddField(
            model_name='zamowienia',
            name='mieszkanie',
            field=models.DecimalField(decimal_places=0, default='0', max_digits=5),
        ),
        migrations.AddField(
            model_name='zamowienia',
            name='telefon',
            field=models.DecimalField(decimal_places=0, default='0', max_digits=9),
        ),
    ]
