# Generated by Django 4.0 on 2021-12-17 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zamowienia', '0002_auto_20211212_1900'),
    ]

    operations = [
        migrations.DeleteModel(
            name='zamowienia',
        ),
    ]
