# Generated by Django 4.0 on 2022-01-04 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zamowienia', '0008_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('oplacone', 'oplacone'), ('przyjete', 'przyjete'), ('przygotowywane', 'przygotowywane'), ('zakonczone', 'zakonczone'), ('dostarczne', 'dostarczane')], default='przyjete', max_length=20),
        ),
    ]
