# Generated by Django 4.0 on 2022-01-04 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zamowienia', '0014_alter_order_date_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('oplacone', 'oplacone'), ('przygotowywane', 'przygotowywane'), ('dostarczne', 'dostarczane'), ('zakonczone', 'zakonczone'), ('przyjete', 'przyjete')], default='przyjete', max_length=20),
        ),
    ]
