# Generated by Django 4.0 on 2022-01-04 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zamowienia', '0015_alter_order_date_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('przygotowywane', 'przygotowywane'), ('dostarczne', 'dostarczane'), ('oplacone', 'oplacone'), ('przyjete', 'przyjete'), ('zakonczone', 'zakonczone')], default='przyjete', max_length=20),
        ),
    ]
