# Generated by Django 4.0 on 2022-01-04 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zamowienia', '0016_alter_order_date_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('zakonczone', 'zakonczone'), ('przygotowywane', 'przygotowywane'), ('przyjete', 'przyjete'), ('oplacone', 'oplacone'), ('dostarczne', 'dostarczane')], default='przyjete', max_length=20),
        ),
    ]
