# Generated by Django 4.0 on 2022-01-04 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zamowienia', '0017_alter_order_date_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('oplacone', 'oplacone'), ('przyjete', 'przyjete'), ('przygotowywane', 'przygotowywane'), ('dostarczane', 'dostarczane'), ('zakonczone', 'zakonczone')], default='przyjete', max_length=20),
        ),
    ]
